### PR TITLE
Update unit_example.py

### PR DESCRIPTION
**Pull request by timgdavies**
Testing against the versioned release schema with the two files below, I believe we should be heading for the model shown above, where units are merged and versioned as a whole object. 

The example illustrates why this is needed, with the change of unit, and second instance missing a label. We would not want the merged data to include the label. 

## Valid file

```json
{
  "publisher": {
    "name": "Public Procurement Authority",
    "scheme": "EX-TEST",
    "uid": "",
    "uri": "http://example.com"
  },
  "license": "http://example.com",
  "publicationPolicy": "http://example.com",
  "publishedDate": "2018-07-25T11:45:01+03:00",
  "uri": "http://example.com",
  "version": "1.1",
  "records": [
    {
      "ocid": "A",
      "releases": [],
      "versionedRelease": {
        "ocid": "A",
        "initiationType": [
          {
            "releaseDate": "2014-01-01T00:00:00Z",
            "releaseID": "1",
            "releaseTag": [
              "tender"
            ],
            "value": "tender"
          }
        ],
        "parties": [
          {
            "id": "consequat reprehenderit",
            "name": [
              {
                "releaseDate": "2014-01-01T00:00:00Z",
                "releaseID": "1",
                "releaseTag": [
                  "award"
                ],
                "value": "sit Lorem irure proident"
              },
              {
                "releaseDate": "2014-01-02T00:00:00Z",
                "releaseID": "1",
                "releaseTag": [
                  "award"
                ],
                "value": "new name"
              }
            ],
            "roles": [
              {
                "releaseDate": "2014-01-01T00:00:00Z",
                "releaseID": "1",
                "releaseTag": [
                  "award"
                ],
                "value": [
                  "buyer"
                ]
              },
              {
                "releaseDate": "2014-01-02T00:00:00Z",
                "releaseID": "1",
                "releaseTag": [
                  "award"
                ],
                "value": [
                  "tenderer"
                ]
              }
            ]
          }
        ],
        "tender": {
          "id": [
            {
              "releaseDate": "2014-01-11T00:00:00Z",
              "releaseID": "1",
              "releaseTag": [
                "tender"
              ],
              "value": "A"
            }
          ],
          "items": [
            {
              "id": "item1",
              "unit": [
                {
                  "releaseDate": "2014-01-01T00:00:00Z",
                  "releaseID": "1",
                  "releaseTag": [
                    "tender"
                  ],
                  "value": {
                    "id": "EA",
                    "scheme": "UNCEFACT",
                    "name": "Each"
                  }
                },
                {
                  "releaseDate": "2014-01-02T00:00:00Z",
                  "releaseID": "2",
                  "releaseTag": [
                    "tender"
                  ],
                  "value": {
                    "id": "TNE",
                    "scheme": "UNCEFACT"
                  }
                }
              ]
            }
          ]
        }
      }
    }
  ]
}
```

## Invalid file

```json
{
  "publisher": {
    "name": "Public Procurement Authority",
    "scheme": "EX-TEST",
    "uid": "",
    "uri": "http://example.com"
  },
  "license": "http://example.com",
  "publicationPolicy": "http://example.com",
  "publishedDate": "2018-07-25T11:45:01+03:00",
  "uri": "http://example.com",
  "version": "1.1",
  "records": [
    {
      "ocid": "A",
      "releases": [],
      "versionedRelease": {
        "ocid": "A",
        "initiationType": [
          {
            "releaseDate": "2014-01-01T00:00:00Z",
            "releaseID": "1",
            "releaseTag": [
              "tender"
            ],
            "value": "tender"
          }
        ],
        "tender": {
          "id": [
            {
              "releaseDate": "2014-01-01",
              "releaseID": "1",
              "releaseTag": [
                "tender"
              ],
              "value": "A"
            }
          ],
          "items": [
            {
              "id": "item1",
              "unit": {
                "id": [
                  {
                    "releaseDate": "2014-01-01",
                    "releaseID": "1",
                    "releaseTag": [
                      "tender"
                    ],
                    "value": "unit_id"
                  },
                  {
                    "releaseDate": "2014-01-02",
                    "releaseID": "2",
                    "releaseTag": [
                      "tender"
                    ],
                    "value": "unit_id_2"
                  }
                ]
              }
            }
          ]
        }
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by kindly** [comment]
To me this seems like a bug in the versioned-release-schema not the merge tool.  
There is no documented mark in the release-schema.json to say this object should be merged as a whole.
The reason it is doing that is that the type is ```['object', 'null']``` and not just ```object``` like all other objects.  The merge tool could use the same logic but otherwise there is nothing to tell the merge tool what to do.

**Comment by kindly** [comment]
Not sure what to do here.
In version 1.1.2 and before the field type was ```object```.  So by changing it to ```['object', 'null']``` we actually made a backwards incompatible change as far as the versioned-release-schema is concerned.
There is nothing in the schema of 1.1.2 and before to differentiate the ```unit``` object from any other object i.e tender.

I personally think this means that there is a bug in the 1.1.3 version-release-schema due to this and the merge tool has the correct behaviour, as it was the correct behaviour in 1.1.2 and before.

**Comment by kindly** [comment]
@jpmckinney yes, my point was that there is an error in ```make_validation_schema.py```. It made a fundamentally different schema in 1.1.3 than in 1.1.2 as it only checked for  ```'object' == prop_type``` and not for  ```'object' in prop_type``` so decided to version the whole object and not individual fields.  

I will raise this issue against the standard.

I do not think there place in the schema that has  ```['object', 'null']``` before 1.1.3 so this bug makes sense.

For this issue I think that the merge tool is correct and the ```make_validation_schema.py``` and therefore the versioned-release-schema in 1.1.3 is wrong, so the example above is wrong in that case.


As a completely separate point, I am not sure I agree with to decision made about ```unit```, as I do not see what makes that object special compared to all other objects,  ```tender```, ```buyer``` ```value``` (and others) are all optional so why do they not have a ```['object', 'null']``` too?
The only difference I see is that unit seems to be the only one that does not have a definition (a ref) but that seems just a jsonschema style anomaly rather than a semantic difference.

**Comment by jpmckinney** [comment]
So, the discussion in open-contracting/standard#630 was:

1. Some required fields are nullable and some optional fields are non-nullable, and this isn't correct.
1. We can't make the required fields non-nullable without a major release: https://github.com/open-contracting/standard/issues/650
1. We can make optional fields nullable *unless* the field refers to a definition. I explain why definitions shouldn't be nullable in https://github.com/open-contracting/ocds-extensions/issues/50#issuecomment-385602144

FYI, the above led to far more changes in extensions than in the standard.

**Comment by kindly** [comment]
I understand the above rational, but I am unconvinced that it should be applied to type `object`.

The merging behaviour is undefined for when you do put a 'null' against an `object` as we have no explicit schema rule to do this at the moment.  
It is especially undefined when considering the `versioned-release-schema` as if you put a null then is the version history lost for the objects properties of that object.
Having `['object', 'null']` work in the way you would expect requires a backwards incompatible change in the `versioned-release-schema`.

**Comment by jpmckinney** [comment]
> The merging behaviour is undefined for when you put a 'null' against an object as we have no explicit schema rule to do this at the moment.

The [bulleted merging rules for objects](http://standard.open-contracting.org/latest/en/schema/merging/#objects) are not explicit about only applying to values that are neither objects nor lists. This should be made explicit if that is the intention. Without that being explicit, I had read "Remove any key that have their value explicitly set to `null` in **new**" (sic) as also applying to keys whose values are objects.

I created https://github.com/open-contracting/ocds-merge/issues/15 so that understanding the merging logic shouldn't require a careful reading of the code. We can then follow-up with more precision in the standard documentation.

What would be the required change to the versioned release validation schema?

To better understand how we got here, were the following erroneously set to `["object", "null"]`?

1. standard: `details`([Feb 2017](https://github.com/open-contracting/standard/commit/6989523e2d07d466a8a74a70cfd650284882a170#diff-0eaeaf6a8f844dc3725590c958f7c127R1232))
1. lots: `LotDetails` ([Feb 2017](https://github.com/open-contracting/ocds_lots_extension/commit/bac216d6d2f7513ec35aa0ad0a513108c1638738#diff-b07d550471924be8c07891e3e566661fR158))
1. metrics: `unit` ([Nov 2016](https://github.com/open-contracting/ocds_metrics_extension/commit/2d903b1a6b7b6e138240e4dc28f8301af6e04bd5#diff-b07d550471924be8c07891e3e566661fR113))
1. tariffs: `unit` ([Dec 2016](https://github.com/open-contracting/ocds_tariffs_extension/commit/d7479c009c60a01635f70dcddb42a853064782fa#diff-b07d550471924be8c07891e3e566661fR32))

I think it's clear that merging rules and versioned releases are not equally understood by everyone (including myself!), and we should at minimum:

1. better document the reference implementation
1. be more precise and/or verbose in the merging rules in the standard documentation

As for fixing the situation we're in, the options seems to be:

1. Change all occurrences of `["object", "null"]` to `["object"]`
1. Define a merging rule to accommodate `["object", "null"]`, and update ocdsmerge

(1) would be backwards-incompatible going back to, at minimum, 1.1.0, when we first used `["object", "null"]` in the standard and core extensions (lots).

I'm in favor of (2), but I don't know yet what the backwards-incompatible change would be (viz above question "What would be the required change to the versioned release validation schema?").

**Comment by kindly** [comment]
> I created #15 so that understanding the merging logic shouldn't require a careful reading of the code. We can then follow-up with more precision in the standard documentation.

I do not think by commenting the code more thoroughly will sort out the issue with understanding or clarifying how merging should/does work.  Code comments should help with other implementation of merging in other languages and people editing this code.  They are not good for defining specifications (even though they could refer to specs).

> What would be the required change to the versioned release validation schema?

Well the good news is that versioned-release-validation-schema.json in 1.1.3 does not have to be changed!
This pull request fixes that we unintentionally versioned the whole of `unit` as one object. 
https://github.com/open-contracting/standard/pull/738/
but that will be the behaviour we actually want now (was not there in 1.1.2 due to type being just 'object').  `unit` is the only `["object", "null"] `in the core standard (apart from `details` but that has no properties so will not effect anything) 

I prototyped an update to to ocds-merge to treat way when type is not `["object"]` and is easy to do.  However, I am not sure what the 'correct' behaviour should be.   We should probably add explicit merge rules to the standard for these cases. The tests also break doing this as 1.1.2 will have different behaviour to 1.1.3 (`unit` has different types in those versions) and we test on older versions of the schema.

**Comment by jpmckinney** [comment]
Ah, nevermind, I see the examples are test fixtures. I'll look at https://github.com/open-contracting/standard/pull/738/

**Comment by jpmckinney** [comment]
As decided in https://github.com/open-contracting/standard/pull/738#issuecomment-440458100, we will not introduce a change in how unit is versioned. That said, the updated fixtures are better tests than the ones we had before, so I've kept the new inputs, but changed the expected outputs.

**Pull request merged**
